mosquito-cr/mosquito

shard.yml
src/external_classes.cr
src/mosquito.cr
src/mosquito/base.cr

Renames granite to match the latest naming on the granite project.

granite::orm -> granite

---

README.md
src/mosquito/job.cr
src/mosquito/queued_job.cr
src/mosquito/serializers/granite.cr
src/mosquito/serializers/primitives.cr
test/mosquito/periodic_job_test.cr
test/mosquito/periodic_task_test.cr
test/mosquito/queued_job_test.cr
test/mosquito/runner_test.cr
test/mosquito/scheduled_job_test.cr
test/mosquito/task_test.cr

This replaces the attempt at a general purpose (de)serializer by case statement with an extensible, customize-able, method based approach.
sort of fixes #16
This opens the door for a wider variety of orms and other object storage mechanisms to easily implement serialization, which will make fixing issues like #15 #14 much easier.
Custom serializers (or serializer overrides) are implemented by defining a pair of methods on a job called `serialize_<type>`. For example, the methods which handle Int32 are:
```crystal
def serialize_int32(value : Int32) : String
value.to_s
end
def deserialize_int32(raw : String) : Int32?
if raw
raw.to_i32
end
end
```
These methods are declared in the abstract Job class, which means that they're override-able too, to your hearts content:
```crystal
class PutsJob …
```

Custom serializers

---

shard.yml
src/mosquito/periodic_task.cr
src/mosquito/queue.cr
src/mosquito/runner.cr
src/mosquito/task.cr
test/mosquito/queue_test.cr
test/mosquito/runner/enqueue_periodic_tasks_test.cr
test/mosquito/runner/start_time_test.cr

This fixes the epoch to unix breaking change.  Also updates deps to the 0.27.0 releases as well.
Running `make test` throw this error tho
```
crystal run test/test_helper.cr test/**/*_test.cr -- --chaos
Module validation failed: !dbg attachment points at wrong subprogram for function
!10 = distinct !DISubprogram(name: "initialize", linkageName: "initialize", scope: !5, file: !5, line: 115, type: !6, isLocal: true, isDefinition: true, scopeLine: 115, isOptimized: false, unit: !0, variables: !2)
void (%"OpenSSL::BIO"*, %TCPSocket*)* @"*OpenSSL::BIO#initialize<TCPSocket>:Nil"
%2 = call i8** @"~OpenSSL::BIO::CRYSTAL_BIO:read"(), !dbg !12
!12 = !DILocation(line: 14, column: 5, scope: !13)
!13 = distinct !DISubprogram(name: "set_data", linkageName: "set_data", scope: !5, file: !5, line: 13, …
```

0.27.0 support

---

LICENSE
README.md
demo/jobs/throttled_job.cr
demo/run.cr
src/mosquito/base.cr
src/mosquito/job.cr
src/mosquito/queue.cr
src/mosquito/runner.cr
test/helpers/mocks.cr
test/mosquito/job_test.cr
test/mosquito/queue_test.cr
test/mosquito/runner/enqueue_delayed_tasks_test.cr
test/mosquito/runner/enqueue_periodic_tasks_test.cr
test/mosquito/runner/fetch_queues_test.cr
test/mosquito/runner/run_tasks_test.cr
test/test_helper.cr

Resolves #1 
* Ability for arbitrary limits/periods.
* Config hash could be used for other things, like retry amounts etc
* Default is no limit 
* ~Maintains state between starts, would have to delete the old config hash to have it set new values~
* Renames the `WAITING` queue to actually be `waiting`, is more clear.
* Refactors the queue methods into a nice macro :)
~However the more i think about it the one thing this wouldn't solve well is if the tasks get added slowly.  For example you have a job that is set to 10 executions per 60 seconds.  But you add one every 10min.  This implementation would still would wait 60 seconds before executing the 11th task.~
This has been solved, it now only counts executions within the given period seconds.
1. I moved the `@@mapping` class var to a …

Ability to throttle jobs

---

shard.yml

This is the rest of the required compatibility for crystal 0.31.1 with #37.

update minitest for crystal 0.31.1 compatibility

---

.circleci/config.yml
shard.yml

This mege request bumps the version number of redis and supports Crystal 0.31.1.

Update redis version to support Crystal 0.31.1

---

src/mosquito/runner.cr
src/mosquito/task.cr
test/helpers/mocks.cr
test/mosquito/runner/run_tasks_test.cr
test/mosquito/task/storage_test.cr

This provides a configurable interface to keep Mosquito from annihilating your redis memory and disk with runaway storage.
By default:
- Tasks which succeed are given a redis TTL of 1, which means they're cleaned up quickly.
- Tasks which are dead lettered are given a redis TTL of 86400, which means they're cleaned up by redis after a wall-clock day.
This behavior is configurable to a point. The dead letter "heap" is theoretical and is composed of tasks which failed so many times they can't be retried. Increasing the failed_job_ttl allows tasks which won't be re-run for whatever reason to live on _longer_ but the deletion is no longer optional. 
-----------------------
This does not cause Mosquito to clean up jobs which it's already forgotten about. If your dead letter heap has already …

Properly cleanup task objects in Redis

---

demo/run.cr
shard.yml
src/mosquito.cr
src/mosquito/redis.cr
src/mosquito/runner.cr
test/mosquito/configuration_test.cr
test/test_helper.cr

Replaces #49 which has been abandoned.

Configure redis_url via configure block (Lucky/habitat integration)

---

src/mosquito/runner.cr
test/helpers/testable_runner.cr
test/mosquito/runner/run_tasks_test.cr

switch to `Time.measure` in place of `Benchmark.measure` for simplification and performance, as alternative to https://github.com/robacarp/mosquito/pull/56
`Benchmark.measure` appears to be slower, compared to `Time.measure`
```crystal
require "benchmark"
Benchmark.ips do |x|
x.report("benchmark") {
Benchmark.measure do
Int64.new(2)
end
}
x.report("time") {
Time.measure do
Int64.new(2)
end
}
end
```
```
benchmark 494.87k (  2.02µs) (± 5.95%)  64.0B/op  27.18× slower
time  13.45M ( 74.34ns) (± 4.62%)   0.0B/op        fastest
```

use Time.measure instead of Benchmark.measure

---

src/mosquito.cr
src/mosquito/runner.cr
test/mosquito/runner/enqueue_periodic_tasks_test.cr

This doesn't completely fix #2 but addresses an inherent problem around the cron scheduler which prevents horizontally scaled mosquito runner architectures.
**Problem**: When running a cluster of workers each worker will try to enqueue cron-scheduled tasks. This results in N enqueues for N workers, which isn't right if you're trying to enqueue a job to run once an hour.
**Solution**: A setting is added to the config block which disables the cron scheduler by early exit. 
```crystal
Mosquito.configure do |settings|
settings.run_cron_scheduler = ENV["MOSQUITO_SCHEDULER"]? || false
end
```
This allows a primitive but workable solution, as long as the deployment infrastructure will guarantee that a worker with the configuration required will be respawn in the event of a failure. Given the …

allows disabling the cron scheduler via settings

---

src/mosquito.cr
src/mosquito/runner.cr
test/mosquito/runner/fetch_queues_test.cr

fixes #2 
When running a worker it's not unreasonable to want to restrict the queues from which it'll execute tasks. This provides a setting which allows whitelisting queue names for monitoring:
```crystal
Mosquito.configure do |settings|
settings.run_from = ["slow_queries"]
end
```
The setting default is `[]` which translates to "run everything". I deliberately didn't implement the spec proposed in #2 to use a regex to filter the queue name because it seems like overkill. I can't imagine a scenario where there are enough queues where filtering explicitly is a configuration maintenance burden.

adds a setting to whitelist the runnable queues for a worker

---

shard.yml
src/mosquito/redis.cr

With the release of `2.8.0` these methods are no longer required https://github.com/stefanwille/crystal-redis/releases/tag/v2.8.0 However, they are called quite a bit, and there will need to be some re-work to switch over the calls.

Update to the latest redis shard version

---

src/mosquito/job.cr
src/mosquito/runner.cr
src/mosquito/task.cr
test/helpers/mocks.cr
test/mosquito/job_test.cr
test/mosquito/runner/idle_wait_test.cr

fixes #59 
This is not strictly part of my push for v2, but it was a small pull request for a feature I've needed a time or two.
I considered moving all of the retry logic to the metaclass since I have a feeling it will be nearly universally constant, but it isn't difficult to imagine scenarios where the response to those questions should be dynamic.

Moves Job retry logic into Job where it can be overridden.

---

demo/jobs/custom_serializers.cr
demo/jobs/periodically_puts.cr
demo/jobs/queued_job.cr
demo/run.cr
src/mosquito/backend.cr
src/mosquito/job.cr
src/mosquito/metadata.cr
src/mosquito/redis_backend.cr
test/mosquito/job_test.cr
test/mosquito/metadata_test.cr
test/mosquito/redis_backend_test.cr

fixes #70 
This implements a `metadata` method on Job which can be used to track statistics, rate limit, or even implement a mutex between workers. The metadata is transparent and relies on the backend to manage any sort of concurrency conflicts.

implements a general purpose job metadata store

---

src/mosquito/job.cr
src/mosquito/queued_job.cr
test/helpers/mocks.cr
test/mosquito/job_test.cr
test/mosquito/queued_job_test.cr

Before hooks allow splitting a jobs execution dynamics into reusable modules -- throttling, etc.
Adapted from https://github.com/luckyframework/avram/blob/ac281f490a85283eaf8b74fd23357dd70a6d7f22/src/avram/callbacks.cr#L122-L152
Thank you @paulcsmith for the reference code. 🍰 
Fixes #69

implements before hooks

---

demo/jobs/rate_limited_job.cr
demo/run.cr
src/mosquito/job.cr
src/mosquito/metadata.cr
src/mosquito/queued_job.cr
src/mosquito/rate_limiter.cr
src/mosquito/task.cr
test/helpers/mocks.cr
test/mosquito/job_test.cr
test/mosquito/metadata_test.cr
test/mosquito/queued_job_test.cr
test/mosquito/rate_limiter_test.cr

This is a re-implementation of the throttling logic introduced in v0.4.0 via #20, but implemented as a decorator module.
The throttling configuration syntax is concise: 
```crystal
class RateLimitedJob < Mosquito::QueuedJob
include Mosquito::RateLimiter
throttle limit: 1, per: 10.seconds
params blah : Int32
def perform
end
end
```
Highlights:
- Leverages `before` hook introduced in 7de390cf160756c16cbd360975786fb4fc698b66 (v0.11.1) so the interface is transparent, and doesn't have any performance penalty on jobs which don't need rate limiting.
- Leverages metadata store introduced in ae67378f9b7c5acaee60fb7df36816e26ea09a8c. The rate limit configuration logic is no longer dangling off of Queue.
- The rate limit key is now override-able, which means that multiple jobs can share the same …

Rate limiter module for jobs

---

demo/run.cr
src/mosquito/runner.cr

This rudimentary interface should help avoid the problem of interrupting a job mid-execution. Fixes #21.

Provides a shutdown method on the runner class

---

CHANGELOG.md
demo/jobs/periodically_puts.cr
demo/jobs/queued_job.cr
src/mosquito/job.cr
src/mosquito/queued_job.cr
src/mosquito/scheduled_job.cr
test/mosquito/job_test.cr

Fixes #84 
This breaking change replaces the `job_type` method with `queue_name`. The functionality is identical but now the purpose of the method is matched by an appropriate name.
The mechanism for storing and declaring the queue has improved a bit too, so this simplifies the code as well. I'm not really sure why the previous implementation was so convoluted.

clarifies the interface for naming the queue a job should use

---

.github/workflows/ci.yml
src/mosquito/job.cr
src/mosquito/periodic_task.cr
src/mosquito/runner.cr
src/mosquito/task.cr
test/helpers/logging_helper.cr
test/helpers/mocks.cr
test/mosquito/job_test.cr
test/mosquito/runner/log_messages_test.cr
test/mosquito/runner/run_tasks_test.cr
test/mosquito/task/storage_test.cr

Logging enhancements

---

src/mosquito/configuration.cr
src/mosquito/runner.cr
test/mosquito/configuration_test.cr
test/mosquito/runner/start_time_test.cr

fixes #99 
Most of this patch is contributed by @jgaskins -- thank you! This is a nice modernization of the mosquito runner code without any change in affect.
related: https://github.com/waterlink/timecop.cr/issues

Updates runner to use time::span

---

.tool-versions
src/mosquito/queued_job.cr

fixes #109 
Assuming a param declaration like this: `param counts : Array(Int32)`, the compile time error message produced will look like this:
I don't think it's possible to write a test for something like this without scaffolding out a way to generate a new mosquito project and compile it.

adds a better error message when a parameter type isn't supported

---

demo/run.cr
src/mosquito/runner.cr

fixes #114 
@mamantoha if you have a moment to verify this works for you, I'd appreciate it.

restores the captive thread behavior of Mosquito::Runner.start

---

CHANGELOG.md
src/mosquito/backend.cr
src/mosquito/redis_backend.cr
src/mosquito/test_backend.cr
test/mosquito/testing_backend_test.cr

fixes #43 
Two approaches were suggested in the issue:
- Run jobs synchronously.
- Catalog jobs that were enqueued, and allow the history to be checked.
The synchronous job pattern is used elsewhere and provides convenience for integration testing. A developer can then test "a user clicks this button and an email is sent to them". However it also adds code to the worker and runner -- something I try to avoid if at all possible to keep mosquito as fast as possible.
I've chosen to implement a testing backend which can be activated in the testing setup code for a project and all enqueues will simply get stored for later inspection / assertion. This avoids adding test_mode=true? checks to worker code. For situations where you need to test the affects of a job, use #run as usual.
It'll look …

Provides a test backend (aka test mode)

---

src/mosquito/redis_backend.cr
test/mosquito/backend/queueing_test.cr
test/mosquito/queue_test.cr
test/mosquito/runners/queue_list_test.cr

One of the most frequent commands issued to the mosquito redis backend is strongly frowned upon by the redis community.
[`keys`](https://redis.io/commands/keys/) is listed as both slow and dangerous because it iterates the entire keyspace in O(n) time.
This replaces `keys` when used to enumerate the list of queues that a mosquito runner should be checking. In a redis server with 10,000 stored keys, listing search queues takes 3-5ms.
After replacing `keys` with `zadd` and `zrangeby`, listing search queues takes 0.3ms. I've chosen to use a sorted set to open up the possibility for automatically pruning the list.
This change is innocuous except in the rare case that a long list of jobs have been enqueued which need to be consumed but are no longer being enqueued. In the rare possibility that …

dramatically decreases the time spent listing queues

---

README.md
demo/run.cr
src/mosquito/configuration.cr
src/mosquito/periodic_job_run.cr
src/mosquito/queue.cr
src/mosquito/runnable.cr
src/mosquito/runner.cr
src/mosquito/runners/coordinator.cr
src/mosquito/runners/executor.cr
src/mosquito/runners/idle_wait.cr
src/mosquito/runners/overseer.cr
src/mosquito/runners/queue_list.cr
test/helpers/logging_helper.cr
test/helpers/mock_coordinator.cr
test/helpers/mock_executor.cr
test/helpers/mock_overseer.cr
test/helpers/mock_queue_list.cr
test/mosquito/queued_job_test.cr
test/mosquito/runnable_test.cr
test/mosquito/runners/executor_test.cr
test/mosquito/runners/overseer_test.cr
test/mosquito/runners/queue_list_test.cr

This will fix #122  #18 and #80
My goal here is to minimally make mosquito network bound workloads significantly faster. Testing with @mamantoha shards.info codebase it’s trivial to cut the scrape time for the whole run by 60-70% because the whole workload is network bound. CPU abound workloads will have almost no benefit here, but the framework is laid for multi process work in the future. 
As always, comments welcome and appreciated.

provides for multiple executors operating under a single runner

---

.github/workflows/ci.yml
src/mosquito/runner.cr

Fixes #126
cf https://github.com/crystal-lang/crystal/issues/9128

sleeps the Mosquito::Runner with `sleep 1` instead of `Fiber.yield`

---

.tool-versions
src/mosquito/backend.cr
src/mosquito/configuration.cr
src/mosquito/key_builder.cr
src/mosquito/periodic_job_run.cr
src/mosquito/redis_backend.cr
test/mosquito/configuration_test.cr

https://github.com/mosquito-cr/mosquito/issues/133
`SCAN_UUID=ryhNEB9tD2K8pvZDdNZKnT ./bin/app`
```Crystal
Mosquito.configure do |settings|
settings.redis_url = ENV["REDIS_URL"]? || "redis://localhost:6379/5"
settings.global_prefix = ENV["SCAN_UUID"]?
end
```
Redis:
```log
1715597220.661123 [5 127.0.0.1:38410] "keys" "ryhNEB9tD2K8pvZDdNZKnT:mosquito:scheduled:*"
1715597220.962453 [5 127.0.0.1:38410] "keys" "ryhNEB9tD2K8pvZDdNZKnT:mosquito:waiting:*"
1715597220.962801 [5 127.0.0.1:38410] "keys" "ryhNEB9tD2K8pvZDdNZKnT:mosquito:scheduled:*"
1715597221.263722 [5 127.0.0.1:38410] "keys" "ryhNEB9tD2K8pvZDdNZKnT:mosquito:waiting:*"
1715597221.263946 [5 127.0.0.1:38410] "keys" "ryhNEB9tD2K8pvZDdNZKnT:mosquito:scheduled:*"
1715597221.565036 [5 127.0.0.1:38410] "keys" …
```

add ability to configure global Redis namespace prefix

---

src/mosquito/job_run.cr

Fixes #135
Running `make test` with the `-Dno_number_autocast` passes with this change. 
I did notice that passing an Int32 was "soft" deprecated
https://github.com/mosquito-cr/mosquito/blob/0107dba08b18670832423f8e8d725b9b4f35db81/src/mosquito/redis_backend.cr#L83-L88
So I can turn this in to `Int64` directly, but in doing that, there was several spots that had to be changed, so I wasn't sure if this is something that is wanting to be done just yet or not.

Ensure only Int numbers are passed to delete and cast to Int64.

---

shard.yml
src/mosquito/redis_backend.cr

The redis shard version requirements of https://github.com/defense-cr/defense conflicts with the requirements of the mosquito shard. 
While trying the tests with the last redis shard version 0.8.0, the new changes in https://github.com/jgaskins/redis/commit/70266be498b1d448594b5ab2eb098600dd70dbb8 triggered failures.
I've included a suggested fix with this PR. 
Feel free to modify / comment for a better solution.

zrange redis command fix + more permissive redis shard version

---

CHANGELOG.md
shard.yml
src/mosquito/configuration.cr
src/mosquito/queue.cr
src/mosquito/redis_backend.cr
src/mosquito/runners/coordinator.cr
src/mosquito/version.cr
test/mosquito/runners/coordinator_test.cr

This is a relatively small but backwards incompatible release, so it's getting a major version tick.

Version 2.0.0 ; removes deprecated 1.x configuration and methods

---

.tool-versions
demo/run.cr
src/mosquito/runnable.cr
src/mosquito/runner.cr
test/mosquito/runners/coordinator_test.cr

fixes #142
The unfortunate placement of the crash in the error message caused mosquito to hang, unable to process any work, but still "running" the sleep loop in the overseer. This patch captures the exception, logs it, and causes mosquito to crash by Crashing the runnable. If it were to happen in an executor, it'll get replaced. Otherwise it'll cause mosquito to terminate.
This will allow third party daemon tooling to monitor and restart mosquito automatically -- monit, systemd, whatever.

Rescue and safely terminate any runnable on unhandle exception

---

src/mosquito/queued_job.cr
test/helpers/mocks.cr
test/mosquito/queued_job_test.cr

fixes #130
You can now use the `before_enqueue` macro to preempt a job from being enqueued -- for example to prevent re-queueing a job if it's already been queued. Or if Jobs should only be run on a certain day of the week, like this:
```crystal
class SomeJob < Mosquito::QueuedJob
param only_run_on : String
before_enqueue do
job.config["only_run_on"] == Time.utc.day_of_week
end
after_enqueue do
end
end
```

implements before/after enqueue hooks on QueuedJob

---

src/mosquito/api.cr
src/mosquito/api/executor.cr
src/mosquito/backend.cr
src/mosquito/metadata.cr
src/mosquito/redis_backend.cr
src/mosquito/runners/executor.cr
src/mosquito/test_backend.cr
test/helpers/mocks.cr
test/mosquito/api/executor_test.cr
test/mosquito/runners/coordinator_test.cr
test/mosquito/runners/executor_test.cr

`Mosquito::Api` is a new module designed to facilitate visibility into a running mosquito cluster. This is the first member class of the module, and it allows inspecting a single executor by ID. 
The `Mosquito::API` is a read-only interface. For an existent `Runner::Executor`, the api allows querying:
- `#current_job` - the job run id that the executor is currently working on
- `#current_job_queue` - the queue which held the job run
- `#last_heartbeat` - a timestamp which was last updated when the executor finished a job run.
The `Runner::Executor` checks in with the API through an interface called `Observability::Executor`, which is the write interface paired with the API.

Adds mosquito api for Executors

---

src/mosquito/api.cr
src/mosquito/api/job_run.cr
test/mosquito/api/job_run_test.cr

For a given Job Run, the Mosquito::Api now allows querying:
- `#runtime_parameters` - the parameters the job was enqueued with
- `#enqueue_time` - a Time representing when the job was added to the queue
- `#retry_count` - how many times the job has failed and been retried

Adds mosquito api for Job Runs

---

shard.yml
src/mosquito/api.cr
src/mosquito/api/executor.cr
src/mosquito/api/overseer.cr
src/mosquito/backend.cr
src/mosquito/configuration.cr
src/mosquito/redis_backend.cr
src/mosquito/runners/overseer.cr
src/mosquito/test_backend.cr
test/mosquito/api/overseer_test.cr
test/mosquito/backend/expiring_list_test.cr
test/mosquito/backend/inspection_test.cr
test/mosquito/backend/overseer_test.cr

The api can:
- get a list of overseers
- for an overseer, get a list of executors
- retrieve the last heartbeat of an overseer

Adds mosquito api for overseers

---

CHANGELOG.md
demo/run.cr
spec/mosquito/api/executor_spec.cr
spec/mosquito/backend/overseer_spec.cr
spec/mosquito/runners/executor_spec.cr
spec/mosquito/runners/overseer_spec.cr
src/mosquito.cr
src/mosquito/api/executor.cr
src/mosquito/api/overseer.cr
src/mosquito/runnable.cr
src/mosquito/runners/coordinator.cr
src/mosquito/runners/executor.cr
src/mosquito/runners/overseer.cr
src/mosquito/runners/queue_list.cr

I spent some time cleaning up the Log output, specifically reducing redundant labeling. On the way it became clear that the real place for most of these logs is in the Observability modules, not on the runner itself. This has proven to be a nice refactor, clarifying the purpose of the Observability mobule and distilling the runner logic by removing the fluff required to inform users of the state.
This changes the log output:
The overseer boot message used to be:
`INFO - mosquito.runners.overseer.4315742080: Overseer<4315742080> is starting`
Now the message is simply:
`INFO - mosquito.overseer: starting`
Similarly, messages from QueueList, Executor, Coordinator, now lack the `.runners.` segment of the tag. Where a runner is likely to be the only instance of that runner within a mosquito …

Cleanup: moves most console log statements into Observability classes

---

spec/mosquito/api/queue_spec.cr
src/mosquito/api.cr
src/mosquito/api/queue.cr
src/mosquito/redis_backend.cr
src/mosquito/test_backend.cr

Currently you can:
- Get a list of queues
- For each queue,
- get the size of the queue (how many jobs are tracked total)
- get the size detail of the queue (how many jobs in each state)
- get a list of the jobs in the queue

Adds mosquito api for interacting with queues

---

spec/helpers/global_helpers.cr
spec/helpers/pub_sub.cr
spec/mosquito/api/executor_spec.cr
spec/spec_helper.cr
src/mosquito/api.cr
src/mosquito/api/executor.cr
src/mosquito/api/observability/publisher.cr
src/mosquito/backend.cr
src/mosquito/base.cr
src/mosquito/redis_backend.cr
src/mosquito/test_backend.cr

This allows a simple real time approach to monitoring a mosquito cluster:
```
ic(1.13.1):pry> c = Mosquito::Api.event_receiver
=> #<Channel(Mosquito::Backend::BroadcastMessage):0x146c30c80>
ic(1.13.1):pry> c.receive
=> Mosquito::Backend::BroadcastMessage(@channel="mosquito:executor:4385634608", @message="{\"event\":\"job-started\",\"job_run\":\"1731083800881:387\",\"from_queue\":\"demo_queue\"}")
```
In this example, after executing `c.receive`, I ran `make demo` in another terminal tab. There's still some reasonable work to be done to queue up messages when the receiver isn't yet listening, but that'll wait until I have a real use case in my hands.

API - executors now publish events

---

spec/helpers/pub_sub.cr
spec/mosquito/api/overseer_spec.cr
src/mosquito/api/overseer.cr
src/mosquito/runners/overseer.cr

fixes #158 
```
ic(1.13.1):pry> subscriber = Mosquito::Api.event_receiver
=> #<Channel(Mosquito::Backend::BroadcastMessage):0x130395ec0>
ic(1.13.1):pry> 4.times { puts subscriber.receive }
Mosquito::Backend::BroadcastMessage(@channel="mosquito:overseer:4337188736", @message="{\"event\":\"executor-created\",\"executor\":4337158448}")
Mosquito::Backend::BroadcastMessage(@channel="mosquito:overseer:4337188736", @message="{\"event\":\"executor-created\",\"executor\":4337158336}")
Mosquito::Backend::BroadcastMessage(@channel="mosquito:overseer:4337188736", @message="{\"event\":\"executor-created\",\"executor\":4337158224}")
Mosquito::Backend::BroadcastMessage(@channel="mosquito:overseer:4337188736", @message="{\"event\":\"starting\"}")
```
Overseers now publish these events:
- Starting
- …

overseers now publish lifecycle events

---

spec/mosquito/api/job_run_spec.cr
spec/mosquito/runners/overseer_spec.cr
src/mosquito/api/job_run.cr
src/mosquito/job_run.cr

job runs now log their started/finished_at times, and that time is retrievable with the API

---

CHANGELOG.md
spec/helpers/logging_helper.cr
spec/mosquito/runnable_spec.cr
src/mosquito/runnable.cr
src/mosquito/runner.cr
src/mosquito/runners/overseer.cr

There are three bugs being fixed here:
- (semantics) the queue_list runner was never being shut down -- there's no meaningful effect on this, except that it might fire off extra commands to redis unnecessarily
- (process hangs after interrupt) if an executor was mid-job during an interrupt, it would cancel it's own shutdown sequence by transitioning back to Waiting after being put into Stopping, and executor would never shutdown and the process would just hang.
- (semantics, premature exit during successful shutdown) assuming the rare condition of an executor _not_ being mid-job during interrupt, the main loop wouldn't block long enough and a full shutdown wouldn't always happen. This is mostly semantics, because the only real loss is a few error messages emitted as part of shutdown.

Safer shutdown sequence
